import 'country.dart';

/// Local dial-code/flag fallback used by the native country picker. Country
/// availability and display names continue to come from GET /countries.
const List<Country> localCountryDialCodes = [
  Country(name: 'Afghanistan', code: 'AF', dialCode: '+93', flag: '🇦🇫'),
  Country(name: 'Albania', code: 'AL', dialCode: '+355', flag: '🇦🇱'),
  Country(name: 'Algeria', code: 'DZ', dialCode: '+213', flag: '🇩🇿'),
  Country(name: 'Andorra', code: 'AD', dialCode: '+376', flag: '🇦🇩'),
  Country(name: 'Angola', code: 'AO', dialCode: '+244', flag: '🇦🇴'),
  Country(name: 'Argentina', code: 'AR', dialCode: '+54', flag: '🇦🇷'),
  Country(name: 'Australia', code: 'AU', dialCode: '+61', flag: '🇦🇺'),
  Country(name: 'Austria', code: 'AT', dialCode: '+43', flag: '🇦🇹'),
  Country(name: 'Belgium', code: 'BE', dialCode: '+32', flag: '🇧🇪'),
  Country(name: 'Benin', code: 'BJ', dialCode: '+229', flag: '🇧🇯'),
  Country(name: 'Botswana', code: 'BW', dialCode: '+267', flag: '🇧🇼'),
  Country(name: 'Brazil', code: 'BR', dialCode: '+55', flag: '🇧🇷'),
  Country(name: 'Burkina Faso', code: 'BF', dialCode: '+226', flag: '🇧🇫'),
  Country(name: 'Cameroon', code: 'CM', dialCode: '+237', flag: '🇨🇲'),
  Country(name: 'Canada', code: 'CA', dialCode: '+1', flag: '🇨🇦'),
  Country(name: 'China', code: 'CN', dialCode: '+86', flag: '🇨🇳'),
  Country(name: 'Colombia', code: 'CO', dialCode: '+57', flag: '🇨🇴'),
  Country(name: 'Egypt', code: 'EG', dialCode: '+20', flag: '🇪🇬'),
  Country(name: 'Ethiopia', code: 'ET', dialCode: '+251', flag: '🇪🇹'),
  Country(name: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷'),
  Country(name: 'Gambia', code: 'GM', dialCode: '+220', flag: '🇬🇲'),
  Country(name: 'Germany', code: 'DE', dialCode: '+49', flag: '🇩🇪'),
  Country(name: 'Ghana', code: 'GH', dialCode: '+233', flag: '🇬🇭'),
  Country(name: 'India', code: 'IN', dialCode: '+91', flag: '🇮🇳'),
  Country(name: 'Ivory Coast', code: 'CI', dialCode: '+225', flag: '🇨🇮'),
  Country(name: 'Indonesia', code: 'ID', dialCode: '+62', flag: '🇮🇩'),
  Country(name: 'Ireland', code: 'IE', dialCode: '+353', flag: '🇮🇪'),
  Country(name: 'Italy', code: 'IT', dialCode: '+39', flag: '🇮🇹'),
  Country(name: 'Japan', code: 'JP', dialCode: '+81', flag: '🇯🇵'),
  Country(name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪'),
  Country(name: 'Liberia', code: 'LR', dialCode: '+231', flag: '🇱🇷'),
  Country(name: 'Mali', code: 'ML', dialCode: '+223', flag: '🇲🇱'),
  Country(name: 'Malawi', code: 'MW', dialCode: '+265', flag: '🇲🇼'),
  Country(name: 'Mexico', code: 'MX', dialCode: '+52', flag: '🇲🇽'),
  Country(name: 'Morocco', code: 'MA', dialCode: '+212', flag: '🇲🇦'),
  Country(name: 'Mozambique', code: 'MZ', dialCode: '+258', flag: '🇲🇿'),
  Country(name: 'Namibia', code: 'NA', dialCode: '+264', flag: '🇳🇦'),
  Country(name: 'Niger', code: 'NE', dialCode: '+227', flag: '🇳🇪'),
  Country(name: 'Netherlands', code: 'NL', dialCode: '+31', flag: '🇳🇱'),
  Country(name: 'New Zealand', code: 'NZ', dialCode: '+64', flag: '🇳🇿'),
  Country(name: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬'),
  Country(name: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰'),
  Country(name: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭'),
  Country(name: 'Poland', code: 'PL', dialCode: '+48', flag: '🇵🇱'),
  Country(name: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹'),
  Country(name: 'Rwanda', code: 'RW', dialCode: '+250', flag: '🇷🇼'),
  Country(name: 'Sierra Leone', code: 'SL', dialCode: '+232', flag: '🇸🇱'),
  Country(name: 'Saudi Arabia', code: 'SA', dialCode: '+966', flag: '🇸🇦'),
  Country(name: 'Senegal', code: 'SN', dialCode: '+221', flag: '🇸🇳'),
  Country(name: 'Singapore', code: 'SG', dialCode: '+65', flag: '🇸🇬'),
  Country(name: 'South Africa', code: 'ZA', dialCode: '+27', flag: '🇿🇦'),
  Country(name: 'South Korea', code: 'KR', dialCode: '+82', flag: '🇰🇷'),
  Country(name: 'Spain', code: 'ES', dialCode: '+34', flag: '🇪🇸'),
  Country(name: 'Tanzania', code: 'TZ', dialCode: '+255', flag: '🇹🇿'),
  Country(name: 'Togo', code: 'TG', dialCode: '+228', flag: '🇹🇬'),
  Country(name: 'Thailand', code: 'TH', dialCode: '+66', flag: '🇹🇭'),
  Country(name: 'Tunisia', code: 'TN', dialCode: '+216', flag: '🇹🇳'),
  Country(name: 'Turkey', code: 'TR', dialCode: '+90', flag: '🇹🇷'),
  Country(name: 'Uganda', code: 'UG', dialCode: '+256', flag: '🇺🇬'),
  Country(name: 'Ukraine', code: 'UA', dialCode: '+380', flag: '🇺🇦'),
  Country(name: 'United Arab Emirates', code: 'AE', dialCode: '+971', flag: '🇦🇪'),
  Country(name: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧'),
  Country(name: 'United States', code: 'US', dialCode: '+1', flag: '🇺🇸'),
  Country(name: 'Zambia', code: 'ZM', dialCode: '+260', flag: '🇿🇲'),
  Country(name: 'Zimbabwe', code: 'ZW', dialCode: '+263', flag: '🇿🇼'),
];
